### ISSUE TITLE
can you help me with your setup

### ISSUE THREAD

**Issue by tjw0lf** [4ban/awesome-ban#1]
Awesome setup i saw your setup on reddit. I grabbed your dotfiles i just want to know how to use the icons and stuff at the top because nothing opens when i click on icon. Also how to change wallpaper on second screen,

if you can help thanks

**Comment by 4ban** [comment]
if you're talking about the buttons right after the tags, then they work as widgets, described in the theme.lua

```
-- Chrome_button
chrome_button = awful.widget.button({ image = theme.chrome })
chrome_button:buttons(awful.util.table.join(
  awful.button({ }, 1, function () awful.util.spawn("google-chrome-stable") end)
))
-- webstorm_button
webstorm_button = awful.widget.button({ image = theme.webstorm })
webstorm_button:buttons(awful.util.table.join(
  awful.button({ }, 1, function () awful.util.spawn("webstorm") end)
))
```
So you just have to install and make sure that it is run by this command `google-chrome-stable`.
Also, check the rules in `rc.lua`. In my setup, it opens in tag number 4. The similar idea for others programmes.

```
{ rule = { class = "Google-chrome" },
      properties = { screen = 1, switchtotag = true, tag = awful.util.tagnames[4] } },
```

And about the second screenshot. It demonstrates the i3lock work. 
First, I have use `xautolock` for automatic lock screen. You can find in the `rc.lua`.
`run_once({ "xautolock -time 10 -locker /home/ban/.config/scripts/lock.sh" })`
And by hotkey.
`awful.key({ modkey            }, "l", function() awful.util.spawn_with_shell("~/.config/scripts/lock.sh") end),`

The script I will add later into the separate folder inside the repo when I will do the full review.
In the meantime, keep the listing:

```
#!/bin/bash

ICON=$HOME/.config/lock.png 
TMPBG=/tmp/screen.png
scrot /tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -u -i $TMPBG%  
```
.config/lock.png - is a [picture of a locker ](https://www.flaticon.com/search?word=lock) with transparent background.

I hope this helped

**Comment by tjw0lf** [comment]
I'm not sure what all that means sorry. But i'm talking about how you normally close a window and file manager and so on etc. There are no buttons to do so

**Comment by 4ban** [comment]
There is a hotkey `win+q` or the buttons on the titlebar for every opened window. 

![7534185d-06b0-48d5-8e40-93aaaf5f42a9](https://user-images.githubusercontent.com/2269864/36084531-279b227c-0f8c-11e8-82a6-0deb4b5f9649.png)

It doesn't work for you?

**Comment by tjw0lf** [comment]
yeah i didn't see them in the batman pro theme, But on your other theme here
https://github.com/4ban/awesome-ban

they were there.

Also i have question with this theme
https://github.com/4ban/awesome-ban

icons on top don't do anything when i click on them

**Comment by 4ban** [comment]
> yeah i didn't see them in the batman pro theme

Because there are no buttons in batman theme. Also, this repository is not relevant to those pro themes.

>icons on top don't do anything when i click on them

About what icons are you talking about?
