### ISSUE TITLE
Crash to fallback on fresh awesome-ban install

### ISSUE THREAD

**Issue by Violettica** [4ban/awesome-ban#12]
# Description

After installing awesome-ban and restarting awesome, I found myself in the default awesome configuration instead of the awesome-ban configuration. There's also an error pop-up at the top right at this time, detailing a Lua error. It's included in the attached screenshot.

# How to reproduce the issue

1. Install awesome.
2. Install awesome-ban, as per the instructions.
3. Start awesome.

# Actual result

Awesome starts in its default configuration, notifying me of an error that occurred.

# Expected result

Awesome starts with the awesome-ban configuration without errors.

# Information

Output of `awesome --version` and `lua -v`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```
```
Lua 5.0.3  Copyright (C) 1994-2006 Tecgraf, PUC-Rio
```

# Screenshots

![Screenshot from 2019-11-08 15-12-10](https://user-images.githubusercontent.com/35011358/68517256-a30bb180-023b-11ea-937f-152e537872ab.png)

**Comment by 4ban** [comment]
Sorry about that. I've changed my laptop years ago and don't use awesomewm anymore. Can't test and fix it
